global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "webapp"
    static_configs:
      - targets: ["webapp:8080"]
    metrics_path: "/metrics"

  - job_name: "windows"
    static_configs:
      - targets: ["host.docker.internal:9182"]
    metrics_path: "/metrics" 